config/routes.rb
Rails.application.routes.draw do
  resources :account_transactions
  root to: "page#index"
  resources :bank_accounts
  resources :clients do
    resources :bank_accounts, controller: "clients/bank_accounts", except: [:index, :show, :destroy]
  end
  namespace :api do
    namespace :v1 do
      post "bank_accounts/new_transaction", to: "bank_accounts#new_transaction"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/account_transactions_controller.rb
class AccountTransactionsController < ApplicationController
  before_action :set_account_transaction, only: [:show, :edit, :update, :destroy]

  # GET /account_transactions
  # GET /account_transactions.json
  def index
    @account_transactions = AccountTransaction.all
  end

  # GET /account_transactions/1
  # GET /account_transactions/1.json
  def show
  end

  # GET /account_transactions/new
  def new
    @account_transaction = AccountTransaction.new
  end

  # GET /account_transactions/1/edit
  def edit
  end

  # POST /account_transactions
  # POST /account_transactions.json
  def create
    @account_transaction = AccountTransaction.new(account_transaction_params)

    respond_to do |format|
      if @account_transaction.save
        format.html { redirect_to @account_transaction, notice: 'Account transaction was successfully created.' }
        format.json { render :show, status: :created, location: @account_transaction }
      else
        format.html { render :new }
        format.json { render json: @account_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_transactions/1
  # PATCH/PUT /account_transactions/1.json
  def update
    respond_to do |format|
      if @account_transaction.update(account_transaction_params)
        format.html { redirect_to @account_transaction, notice: 'Account transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_transaction }
      else
        format.html { render :edit }
        format.json { render json: @account_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_transactions/1
  # DELETE /account_transactions/1.json
  def destroy
    @account_transaction.destroy
    respond_to do |format|
      format.html { redirect_to account_transactions_url, notice: 'Account transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_transaction
      @account_transaction = AccountTransaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_transaction_params
      params.require(:account_transaction).permit(:amount, :transaction_type, :bank_account_id)
    end
end

app/helpers/account_transactions_helper.rb
module AccountTransactionsHelper
end

app/views/account_transactions/_form.html.erb
<%= form_for(@account_transaction, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @account_transaction.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@account_transaction.errors.count, "error") %> prohibited this account_transaction from being saved:</h4>

      <ul>
      <% @account_transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :amount, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :amount, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :transaction_type, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :transaction_type, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bank_account, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :bank_account, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/account_transactions/_form.html.haml
= form_for(@account_transaction, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @account_transaction.errors.any?
    .alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4
        = pluralize(@account_transaction.errors.count, "error")
        prohibited this account_transaction from being saved:
      %ul
        - @account_transaction.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :amount, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :amount, class: "form-control"
  .form-group
    = f.label :transaction_type, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :transaction_type, class: "form-control"
  .form-group
    = f.label :bank_account, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :bank_account, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/account_transactions/edit.html.erb
<div class="page-header">
  <%= link_to account_transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @account_transaction, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing account_transaction</h1>
</div>

<%= render 'form' %>

app/views/account_transactions/edit.html.haml
.page-header
  = link_to account_transactions_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @account_transaction, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing account_transaction
= render 'form'

app/views/account_transactions/index.html.erb
<div class="page-header">
  <%= link_to new_account_transaction_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Account transaction
  <% end %>
  <h1>Listing account_transactions</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Amount</th>
            <th>Transaction type</th>
            <th>Bank account</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @account_transactions) do |account_transaction| %>
            <td><%= account_transaction.amount %></td>
            <td><%= account_transaction.transaction_type %></td>
            <td><%= account_transaction.bank_account %></td>
            <td><%= link_to 'Show', account_transaction %></td>
        <td><%= link_to 'Edit', edit_account_transaction_path(account_transaction) %></td>
        <td><%= link_to 'Destroy', account_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/account_transactions/index.html.haml
.page-header
  = link_to new_account_transaction_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Account transaction
  %h1 Listing account_transactions
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Amount
        %th Transaction type
        %th Bank account
        %th
        %th
        %th
    %tbody
      = content_tag_for(:tr, @account_transactions) do |account_transaction|
        %td= account_transaction.amount
        %td= account_transaction.transaction_type
        %td= account_transaction.bank_account
        %td= link_to 'Show', account_transaction
        %td= link_to 'Edit', edit_account_transaction_path(account_transaction)
        %td= link_to 'Destroy', account_transaction, method: :delete, data: { confirm: 'Are you sure?' }

app/views/account_transactions/new.html.erb
<div class="page-header">
  <%= link_to account_transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New account_transaction</h1>
</div>

<%= render 'form' %>

app/views/account_transactions/new.html.haml
.page-header
  = link_to account_transactions_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New account_transaction
= render 'form'

app/views/account_transactions/show.html.erb
<div class="page-header">
  <%= link_to account_transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_account_transaction_path(@account_transaction), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show account_transaction</h1>
</div>

<dl class="dl-horizontal">
  <dt>Amount:</dt>
  <dd><%= @account_transaction.amount %></dd>

  <dt>Transaction type:</dt>
  <dd><%= @account_transaction.transaction_type %></dd>

  <dt>Bank account:</dt>
  <dd><%= @account_transaction.bank_account %></dd>

</dl>

app/views/account_transactions/show.html.haml
.page-header
  = link_to account_transactions_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_account_transaction_path(@account_transaction), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show account_transaction
%dl.dl-horizontal
  %dt Amount:
  %dd= @account_transaction.amount
  %dt Transaction type:
  %dd= @account_transaction.transaction_type
  %dt Bank account:
  %dd= @account_transaction.bank_account