config/routes.rb
Rails.application.routes.draw do
  resources :account_transactions
  root to: "page#index"
  resources :bank_accounts
  resources :clients do
    resources :bank_accounts, controller: "clients/bank_accounts", except: [:index, :show, :destroy]
  end
  namespace :api do
    namespace :v1 do
      post "bank_accounts/new_transaction", to: "bank_accounts#new_transaction"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/clients/bank_accounts_controller.rb
module Clients
    class BankAccountsController < ApplicationController
        before_action :load_parent_object
        before_action :load_object, only: [:edit, :update]

        def new
            @bank_account = BankAccount.new
        end

        def create
            @bank_account = BankAccount.new(bank_account_params)
            @bank_account.client = @client

            if @bank_account.save
                redirect_to bank_account_path(@bank_account.id)
            else
                render "new"
            end
        end

        def edit
        end

        def update
            @bank_account.client = @client

            if @bank_account.update(bank_account_params)
                redirect_to bank_account_path(@bank_account.id)
            else
                render "edit"
            end
        end
        
        private
        def load_object
            @bank_account = BankAccount.find(params[:id])
        end

        def load_parent_object
            @client = Client.find(params[:client_id])
        end

        def bank_account_params
            params.require(:bank_account).permit(:account_number)
        end
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :middle_name, :cliente_number)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_bank_accounts.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Account Number</th>
      <th>Balance</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% bank_accounts.each do |bank_account| %>
      <tr>
        <td>#{bank_account.account_number}</td>
        <td>#{number_to_currency(bank_account.balance, unit: "$")}</td>
        <td>
          <%= link_to bank_account_path(bank_account.id), class: "btn btn-info" do %>
            Show
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/_form.html.erb
<%= form_for(@client, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @client.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h4>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :middle_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :middle_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cliente_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cliente_number, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/clients/_list.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Client Number</th>
      <th>Name</th>
      <th>Number of Accounts</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% clients.each do |c| %>
      <tr>
        <td>#{c.client_number}</td>
        <td>#{c}</td>
        <td>#{c.num_accounts}</td>
        <td>
          <%= link_to client_path(c.id), class: "btn btn-primary" do %>
            Show
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/edit.html.erb
<div class="page-header">
  <%= link_to clients_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @client, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing client</h1>
</div>

<%= render 'form' %>

app/views/clients/index.html.erb
<div class="page-header">
  <%= link_to new_client_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Client
  <% end %>
  <h1>Listing clients</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Middle name</th>
            <th>Cliente number</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @clients) do |client| %>
            <td><%= client.first_name %></td>
            <td><%= client.last_name %></td>
            <td><%= client.middle_name %></td>
            <td><%= client.cliente_number %></td>
            <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clients/new.html.erb
<div class="page-header">
  <%= link_to clients_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New client</h1>
</div>

<%= render 'form' %>

app/views/clients/show.html.erb
<div class="page-header">
  <%= link_to clients_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_client_path(@client), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show client</h1>
</div>

<dl class="dl-horizontal">
  <dt>First name:</dt>
  <dd><%= @client.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @client.last_name %></dd>

  <dt>Middle name:</dt>
  <dd><%= @client.middle_name %></dd>

  <dt>Cliente number:</dt>
  <dd><%= @client.cliente_number %></dd>

</dl>