config/routes.rb
Rails.application.routes.draw do
  resources :account_transactions
  root to: "page#index"
  resources :bank_accounts
  resources :clients do
    resources :bank_accounts, controller: "clients/bank_accounts", except: [:index, :show, :destroy]
  end
  namespace :api do
    namespace :v1 do
      post "bank_accounts/new_transaction", to: "bank_accounts#new_transaction"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :clientes
end

app/controllers/api/V1/bank_accounts_controller.rb
module Api 
    module V1 
        class BankAccountsController < ApplicationController
            skip_before_action :verify_authenticity_token

            def new_transaction
                amount = params[:amount]
                transaction_type = params[:transaction_type]
                bank_account_id = params[:bank_account_id]

                errors = ::BankAccounts::ValidateNewTransaction.new(
                    amount: amount,
                    transaction_type: transaction_type,
                    bank_account_id: bank_account_id
                ).execute!

                if errors.size > 0
                    render json: { errors: errors }, status: 402
                else
                    bank_account = ::BankAccounts::PerformTransaction.new(
                        amount: amount,
                        transaction_type: transaction_type,
                        bank_account_id: bank_account_id
                    ).execute!

                    render json: { balance: bank_account.balance }
                end
            end
        end
    end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  # GET /bank_accounts.json
  def index
    @bank_accounts = BankAccount.all
  end

  # GET /bank_accounts/1
  # GET /bank_accounts/1.json
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully created.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.json
  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to bank_accounts_url, notice: 'Bank account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_account_params
      params.require(:bank_account).permit(:balance, :account_number, :clientes_id)
    end
end

app/controllers/clients/bank_accounts_controller.rb
module Clients
    class BankAccountsController < ApplicationController
        before_action :load_parent_object
        before_action :load_object, only: [:edit, :update]

        def new
            @bank_account = BankAccount.new
        end

        def create
            @bank_account = BankAccount.new(bank_account_params)
            @bank_account.client = @client

            if @bank_account.save
                redirect_to bank_account_path(@bank_account.id)
            else
                render "new"
            end
        end

        def edit
        end

        def update
            @bank_account.client = @client

            if @bank_account.update(bank_account_params)
                redirect_to bank_account_path(@bank_account.id)
            else
                render "edit"
            end
        end
        
        private
        def load_object
            @bank_account = BankAccount.find(params[:id])
        end

        def load_parent_object
            @client = Client.find(params[:client_id])
        end

        def bank_account_params
            params.require(:bank_account).permit(:account_number)
        end
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_form.html.erb
<%= form_for(@bank_account, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @bank_account.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@bank_account.errors.count, "error") %> prohibited this bank_account from being saved:</h4>

      <ul>
      <% @bank_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :balance, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :balance, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :account_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :account_number, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :clientes, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :clientes, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bank_accounts/_modal_transaction.html.erb
<div class="modal fade modal-fade" id="modal-transaction">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data="<%= {dismiss:'modal' %>" type="button">}
          <span aria="<%= {hidden:'true' %>">}
            <i class="fa fa-close"></i>
          </span>
          <span class="sr-only">Close</span>
        </button>
        <div class="row">
          <div class="col-md-12">
            <h4 class="modal-title"></h4>
          </div>
          New Transaction
        </div>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <div class="notification"></div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <label>
              Amount
              <%= text_field_tag :amount, 0.00, id: "input-amount", class: "form-control" %>
            </label>
          </div>
          <div class="col-md-6">
            <label>
              Transaction Type
              <%= select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: "select-transaction-type", class: "form-control" %>
            </label>
          </div>
          <div class="modal-footer">
            <button class="btn btn-default" data="<%= {dismiss:'modal' %>" type="button">} Close</button>
            <button class="btn btn-primary" id="btn-save" type="button">Save</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bank_accounts/_transactions.html.erb
<div class="modal fade modal-fade" id="modal-transaction">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data="<%= {dismiss:'modal' %>" type="button">}
          <span aria="<%= {hidden:'true' %>">}
            <i class="fa fa-close"></i>
          </span>
          <span class="sr-only">Close</span>
        </button>
        <div class="row">
          <div class="col-md-12">
            <h4 class="modal-title"></h4>
          </div>
          New Transaction
        </div>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <div class="notification"></div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <label>
              Amount
              <%= text_field_tag :amount, 0.00, id: "input-amount", class: "form-control" %>
            </label>
          </div>
          <div class="col-md-6">
            <label>
              Transaction Type
              <%= select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: "select-transaction-type", class: "form-control" %>
            </label>
          </div>
          <div class="modal-footer">
            <button class="btn btn-default" data="<%= {dismiss:'modal' %>" type="button">} Close</button>
            <button class="btn btn-primary" id="btn-save" type="button">Save</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bank_accounts/edit.html.erb
<div class="page-header">
  <%= link_to bank_accounts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @bank_account, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing bank_account</h1>
</div>

<%= render partial: "form", locals: { bank_account: @bank_account }%>

app/views/bank_accounts/index.html.erb
<div class="page-header">
  <%= link_to new_bank_account_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Bank account
  <% end %>
  <h1>Listing bank_accounts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Balance</th>
            <th>Account number</th>
            <th>Clientes</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @bank_accounts) do |bank_account| %>
            <td><%= bank_account.balance %></td>
            <td><%= bank_account.account_number %>
            <%= link_to client_path(bank_account.id) do  {bank_account.client} %>
            </td>
            <td><%= bank_account.clientes %>
            <%= link_to client_path(bank_account.id) do {bank_account.client} %>
            </td>
            <td><%= link_to 'Show', bank_account_path(bank_account.id) %></td>
        <td><%= link_to 'Edit', edit_bank_account_path(bank_account.id) %></td>
        <td><%= link_to 'Destroy', bank_account_path(bank_account.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bank_accounts/index.html.haml
%script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
%script{:crossorigin => "anonymous", :integrity => "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"}
%script{:crossorigin => "anonymous", :integrity => "sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"}
%link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css", :integrity => "sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B", :rel => "stylesheet"}/
%h1
 Bank Accounts

= link_to new_bank_account_path, class: "btn btn-primary" do 
 New Bank Account

%table.table.table-bordered
 %thread
  %tr 
   %th Account Number
   %th Client
   %th Balance
   %th Actions
 %tbody
  - @bank_accounts.each do |bank_account|
   %tr 
    %td #{bank_account.account_number}
    %td
     = link_to client_path(bank_account.id) do
      #{bank_account.client}
    %td #{number_to_currency(bank_account.balance, unit: "$")}
    %td
     = link_to bank_account_path(bank_account.id), class: "btn btn-primary" do
      Show

app/views/bank_accounts/new.html.erb
<div class="page-header">
  <%= link_to bank_accounts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New bank_account</h1>
</div>

<%= render 'form' %>

app/views/bank_accounts/show.html.erb
<div class="page-header">
  <h1>
  Account Number: #{@bank_account.account_number}
  </h1>
  <small>#{@bank_account.client}</small>
  <%= link_to bank_accounts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_bank_account_path(@bank_account.id), class: "btn btn-info" do  %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  
  <h1>Show bank_account</h1>
  <%= javascript_include_tag "bank_accounts/Show" %>
  <script>

      $(document).ready(function() {
        Show.init();
      });te

  </script>
  <%= link_to bank_accounts_path, method: :delete %>
  <%= button_tag :new_transaction, id: "btn-new-transaction", class: "btn btn-primary" do %>
  New Transaction
    <%= link_to bank_accounts_path, class: "btn btn-primary" do  %>
    Back To Bank Accounts
  <% end %>
  <%= render partial: "transactions", locals: { bank_account: @bank_account } %>
<% end %>
</div>

<dl class="dl-horizontal">
  <dt>Balance:</dt>
  <dd><%= @bank_account.balance %></dd>

  <dt>Account number:</dt>
  <dd><%= @bank_account.account_number %></dd>
  <small></small>
  <dt>Clientes:</dt>
  <dd><%= @bank_account.clientes %></dd>
 


</dl>